[project]
name = "trading"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "backtrader>=1.9.78.123",
    "ipykernel>=6.29.5",
    "mplfinance>=0.12.10b0",
    "yfinance>=0.2.51",
]
